/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaquiz;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Question1
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl_q1 = new javax.swing.JPanel();
        pnl_title = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        btn_play6 = new javax.swing.JButton();
        btn_play7 = new javax.swing.JButton();
        btn_play8 = new javax.swing.JButton();
        btn_play9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_q1.setBackground(new java.awt.Color(255, 255, 255));
        pnl_q1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnl_q1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_title.setBackground(new java.awt.Color(0, 0, 0));
        pnl_title.setForeground(new java.awt.Color(255, 102, 0));

        lbl_title.setBackground(new java.awt.Color(255, 255, 255));
        lbl_title.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Main Menu");

        javax.swing.GroupLayout pnl_titleLayout = new javax.swing.GroupLayout(pnl_title);
        pnl_title.setLayout(pnl_titleLayout);
        pnl_titleLayout.setHorizontalGroup(
            pnl_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_titleLayout.setVerticalGroup(
            pnl_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_q1.add(pnl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        btn_play6.setBackground(new java.awt.Color(0, 0, 0));
        btn_play6.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        btn_play6.setForeground(new java.awt.Color(255, 255, 255));
        btn_play6.setText("ABOUT");
        btn_play6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_play6ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_play6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 90, 30));

        btn_play7.setBackground(new java.awt.Color(0, 0, 0));
        btn_play7.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        btn_play7.setForeground(new java.awt.Color(255, 255, 255));
        btn_play7.setText("PLAY");
        btn_play7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_play7ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_play7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 90, 30));

        btn_play8.setBackground(new java.awt.Color(0, 0, 0));
        btn_play8.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        btn_play8.setForeground(new java.awt.Color(255, 255, 255));
        btn_play8.setText("HISTORY");
        btn_play8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_play8ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_play8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 90, 30));

        btn_play9.setBackground(new java.awt.Color(0, 0, 0));
        btn_play9.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        btn_play9.setForeground(new java.awt.Color(255, 255, 255));
        btn_play9.setText("RULES");
        btn_play9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_play9ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_play9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 90, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\JavaQuiz\\src\\javaquiz\\image\\bg_menu.png")); // NOI18N
        pnl_q1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_play6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_play6ActionPerformed
        new About().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btn_play6ActionPerformed

    private void btn_play7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_play7ActionPerformed
        new Levels(0).setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btn_play7ActionPerformed

    private void btn_play8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_play8ActionPerformed
        new History_Quiz().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btn_play8ActionPerformed

    private void btn_play9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_play9ActionPerformed
        new Rules().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btn_play9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_play6;
    private javax.swing.JButton btn_play7;
    private javax.swing.JButton btn_play8;
    private javax.swing.JButton btn_play9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel pnl_q1;
    private javax.swing.JPanel pnl_title;
    // End of variables declaration//GEN-END:variables
}
