/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaquiz;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Start extends javax.swing.JFrame {
int i;
    /**
     * Creates new form Question1
     */
    public Start(int i) {
        initComponents();
        this.i=i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl_q1 = new javax.swing.JPanel();
        pnl_title = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        btn_play = new javax.swing.JButton();
        lbl_gdlck = new javax.swing.JLabel();
        btn_play1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_q1.setBackground(new java.awt.Color(255, 255, 255));
        pnl_q1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnl_q1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_title.setBackground(new java.awt.Color(0, 0, 0));
        pnl_title.setForeground(new java.awt.Color(255, 102, 0));

        lbl_title.setBackground(new java.awt.Color(255, 255, 255));
        lbl_title.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Start Quiz");

        javax.swing.GroupLayout pnl_titleLayout = new javax.swing.GroupLayout(pnl_title);
        pnl_title.setLayout(pnl_titleLayout);
        pnl_titleLayout.setHorizontalGroup(
            pnl_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_titleLayout.setVerticalGroup(
            pnl_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_q1.add(pnl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        btn_play.setBackground(new java.awt.Color(0, 0, 0));
        btn_play.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        btn_play.setForeground(new java.awt.Color(255, 255, 255));
        btn_play.setText("PLAY");
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 73, 30));

        lbl_gdlck.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        lbl_gdlck.setText("\"Are you ready\"");
        pnl_q1.add(lbl_gdlck, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        btn_play1.setBackground(new java.awt.Color(0, 0, 0));
        btn_play1.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        btn_play1.setForeground(new java.awt.Color(255, 255, 255));
        btn_play1.setText("HOME");
        btn_play1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_play1ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_play1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 73, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\JavaQuiz\\src\\javaquiz\\image\\bg_menu.png")); // NOI18N
        pnl_q1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        if (i==1){new L1_Question1().setVisible(true); this.dispose();}
        else if (i==2){new L2_Question1().setVisible(true); this.dispose();}
        else if (i==3){new L3_Question1().setVisible(true); this.dispose();}
        else if (i==4){new L4_Question1().setVisible(true); this.dispose();}
        else if (i==5){new L5_Question1().setVisible(true); this.dispose();}
        else if (i==6){new L6_Question1().setVisible(true); this.dispose();}
        else if (i==7){new L7_Question1().setVisible(true); this.dispose();}
        else if (i==8){new L8_Question1().setVisible(true); this.dispose();}
        
    }//GEN-LAST:event_btn_playActionPerformed

    private void btn_play1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_play1ActionPerformed
        new MainMenu().setVisible(true); this.dispose();
    }//GEN-LAST:event_btn_play1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_play1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_gdlck;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel pnl_q1;
    private javax.swing.JPanel pnl_title;
    // End of variables declaration//GEN-END:variables
}
