/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaquiz;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Levels extends javax.swing.JFrame {
    int i;
    int cek=0;
    /**
     * Creates new form Question1
     */
    public Levels(int i) {
        initComponents();
        this.i=i;
        
    }
    
         public void tampil_data(){
        List data = new class_player().tampil_data();
        Object[] a = data.toArray();
        String[] sl = (String[]) data.toArray(new String[0]);
        
        for(int x =0; x<sl.length; x=x+6){
            if(sl[x+1].equals(String.format("%d", i-1)) && sl[x+4].equals("100"))
            {
                cek=1;
                break;
            }
        }
        
    }
         
         
         
         
         
         
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl_q1 = new javax.swing.JPanel();
        pnl_title = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        btn_level1 = new javax.swing.JButton();
        btn_level2 = new javax.swing.JButton();
        btn_level4 = new javax.swing.JButton();
        btn_level3 = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        btn_level5 = new javax.swing.JButton();
        btn_level6 = new javax.swing.JButton();
        btn_level8 = new javax.swing.JButton();
        btn_level7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_q1.setBackground(new java.awt.Color(255, 255, 255));
        pnl_q1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnl_q1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_title.setBackground(new java.awt.Color(0, 0, 0));
        pnl_title.setForeground(new java.awt.Color(255, 102, 0));

        lbl_title.setBackground(new java.awt.Color(51, 51, 51));
        lbl_title.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Levels of Choice");

        javax.swing.GroupLayout pnl_titleLayout = new javax.swing.GroupLayout(pnl_title);
        pnl_title.setLayout(pnl_titleLayout);
        pnl_titleLayout.setHorizontalGroup(
            pnl_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_titleLayout.setVerticalGroup(
            pnl_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_q1.add(pnl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        btn_level1.setBackground(new java.awt.Color(0, 0, 0));
        btn_level1.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        btn_level1.setForeground(new java.awt.Color(255, 255, 255));
        btn_level1.setText("1");
        btn_level1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_level1ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 77, 65, 65));

        btn_level2.setBackground(new java.awt.Color(0, 0, 0));
        btn_level2.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        btn_level2.setForeground(new java.awt.Color(255, 255, 255));
        btn_level2.setText("2");
        btn_level2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_level2ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 77, 65, 65));

        btn_level4.setBackground(new java.awt.Color(0, 0, 0));
        btn_level4.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        btn_level4.setForeground(new java.awt.Color(255, 255, 255));
        btn_level4.setText("4");
        btn_level4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_level4ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_level4, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 77, 65, 65));

        btn_level3.setBackground(new java.awt.Color(0, 0, 0));
        btn_level3.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        btn_level3.setForeground(new java.awt.Color(255, 255, 255));
        btn_level3.setText("3");
        btn_level3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_level3ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_level3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 77, 65, 65));

        btn_home.setBackground(new java.awt.Color(0, 0, 0));
        btn_home.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setText("HOME");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 255, 75, 30));

        btn_level5.setBackground(new java.awt.Color(0, 0, 0));
        btn_level5.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        btn_level5.setForeground(new java.awt.Color(255, 255, 255));
        btn_level5.setText("5");
        btn_level5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_level5ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_level5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 153, 65, 65));

        btn_level6.setBackground(new java.awt.Color(0, 0, 0));
        btn_level6.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        btn_level6.setForeground(new java.awt.Color(255, 255, 255));
        btn_level6.setText("6");
        btn_level6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_level6ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_level6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 153, 65, 65));

        btn_level8.setBackground(new java.awt.Color(0, 0, 0));
        btn_level8.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        btn_level8.setForeground(new java.awt.Color(255, 255, 255));
        btn_level8.setText("8");
        btn_level8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_level8ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_level8, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 153, 65, 65));

        btn_level7.setBackground(new java.awt.Color(0, 0, 0));
        btn_level7.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        btn_level7.setForeground(new java.awt.Color(255, 255, 255));
        btn_level7.setText("7");
        btn_level7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_level7ActionPerformed(evt);
            }
        });
        pnl_q1.add(btn_level7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 153, 65, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\JavaQuiz\\src\\javaquiz\\image\\bg_menu.png")); // NOI18N
        pnl_q1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_level1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_level1ActionPerformed
        new Start(1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_level1ActionPerformed

    private void btn_level2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_level2ActionPerformed
        this.i=2;
        tampil_data();
        if(cek==1){
        new Start(2).setVisible(true);
        this.dispose(); }
        
         else {JOptionPane.showMessageDialog(null, "Complete the previous level !"); }
    }//GEN-LAST:event_btn_level2ActionPerformed

    private void btn_level4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_level4ActionPerformed
        this.i=4;
        tampil_data();
        if(cek==1){
        new Start(4).setVisible(true);
        this.dispose(); }
        
         else {JOptionPane.showMessageDialog(null, "Complete the previous level !"); }
    }//GEN-LAST:event_btn_level4ActionPerformed

    private void btn_level3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_level3ActionPerformed
        this.i=3;
        tampil_data();
        if(cek==1){
        new Start(3).setVisible(true);
        this.dispose(); }
        
        else {JOptionPane.showMessageDialog(null, "Complete the previous level !"); }
    }//GEN-LAST:event_btn_level3ActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_level5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_level5ActionPerformed
        this.i=5;
        tampil_data();
        if(cek==1){
        new Start(5).setVisible(true);
        this.dispose(); }
        
        else {JOptionPane.showMessageDialog(null, "Complete the previous level !"); }
    }//GEN-LAST:event_btn_level5ActionPerformed

    private void btn_level6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_level6ActionPerformed
        this.i=6;
        tampil_data();
        if(cek==1){
        new Start(6).setVisible(true);
        this.dispose(); }
        
         else {JOptionPane.showMessageDialog(null, "Complete the previous level !"); }
    }//GEN-LAST:event_btn_level6ActionPerformed

    private void btn_level8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_level8ActionPerformed
        this.i=8;
        tampil_data();
        if(cek==1){
        new Start(8).setVisible(true);
        this.dispose(); }
        
         else {JOptionPane.showMessageDialog(null, "Complete the previous level !"); }
    }//GEN-LAST:event_btn_level8ActionPerformed

    private void btn_level7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_level7ActionPerformed
        this.i=7;
        tampil_data();
        if(cek==1){
        new Start(7).setVisible(true);
        this.dispose(); }
        
         else {JOptionPane.showMessageDialog(null, "Complete the previous level !"); }
    }//GEN-LAST:event_btn_level7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Levels(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_level1;
    private javax.swing.JButton btn_level2;
    private javax.swing.JButton btn_level3;
    private javax.swing.JButton btn_level4;
    private javax.swing.JButton btn_level5;
    private javax.swing.JButton btn_level6;
    private javax.swing.JButton btn_level7;
    private javax.swing.JButton btn_level8;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel pnl_q1;
    private javax.swing.JPanel pnl_title;
    // End of variables declaration//GEN-END:variables
}
