/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaquiz;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Splash_quiz extends javax.swing.JFrame {

    /**
     * Creates new form Question1
     */
    public Splash_quiz() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_title1 = new javax.swing.JLabel();
        pnl_q1 = new javax.swing.JPanel();
        loadingbar = new javax.swing.JProgressBar();
        loadingnumber = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        lbl_title3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        lbl_title1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_title1.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        lbl_title1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title1.setText("WELCOME IN WAWASAN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_q1.setBackground(new java.awt.Color(255, 255, 255));
        pnl_q1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnl_q1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingbar.setForeground(new java.awt.Color(0, 0, 0));
        loadingbar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        pnl_q1.add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 240, 20));

        loadingnumber.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        loadingnumber.setText("100%");
        pnl_q1.add(loadingnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel1.setText("wait a moment . . .");
        pnl_q1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        lbl_title2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_title2.setFont(new java.awt.Font("Freehand521 BT", 1, 24)); // NOI18N
        lbl_title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title2.setText("Welcome In");
        pnl_q1.add(lbl_title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 376, 50));

        lbl_title.setBackground(new java.awt.Color(255, 255, 255));
        lbl_title.setFont(new java.awt.Font("Algerian", 1, 26)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("QUIZ");
        pnl_q1.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 390, -1));

        lbl_title3.setBackground(new java.awt.Color(255, 255, 255));
        lbl_title3.setFont(new java.awt.Font("Algerian", 1, 26)); // NOI18N
        lbl_title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title3.setText("Wawasan Nusantara");
        pnl_q1.add(lbl_title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 390, -1));

        jLabel3.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel3.setText("OPENING");
        pnl_q1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\JavaQuiz\\src\\javaquiz\\image\\bg_menu.png")); // NOI18N
        pnl_q1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_q1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Splash_quiz SPLASH = new Splash_quiz();
        SPLASH.setVisible(true); 
        
        MainMenu menu = new MainMenu();
        
        try{
            int i=0;
            for (i=0; i<=100; i=i+5){
                Thread.sleep(60);
                SPLASH.loadingnumber.setText(Integer.toString(i) + "%");
                SPLASH.loadingbar.setValue(i);
            }
            
        }catch (Exception e){
        }
        
        menu.setVisible(true); 
        SPLASH.dispose();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash_quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JLabel lbl_title3;
    private javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel loadingnumber;
    private javax.swing.JPanel pnl_q1;
    // End of variables declaration//GEN-END:variables
}
